name: Deploy Frontend to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/marco/prosthetic

          if [ -d "prosthetic-compose" ]; then
            cd prosthetic-compose
            git pull origin master
          else
            git clone git@github.com:prosthetic-team/prosthetic-compose.git
            cd prosthetic-compose
          fi

          docker compose -f docker-compose.yml up -d --build 
